version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Python linter 
          command: python3 -m py_compile unsuspend-tickets.py

